// <auto-generated />
using Maison_Sucree.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maison_Sucree.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221122036_AddImage")]
    partial class AddImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maison_Sucree.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Chocolate",
                            Description = "Ou artizanal din ciocolată fină, umplut cu cremă catifelată de ciocolată și decorat cu căpșuni proaspete și trufe crocante. Desert premium perfect pentru ocazii speciale.",
                            ImageUrl = "/images/products/strawberry_chocolate_egg.png",
                            Name = "Strawberry Chocolate Egg",
                            Price = 12.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Cake",
                            Description = "Mini prăjituri Red Velvet cu straturi delicate de blat catifelat și cremă fină de vanilie, decorate cu fructe proaspete. Un desert elegant, perfect pentru momente speciale.",
                            ImageUrl = "/images/products/red_velvet.png",
                            Name = "Red Velvet Cream Petits",
                            Price = 13.5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Candy",
                            Description = "Mini delicii din ciocolată fină, umplute cu cremă catifelată de vanilie și decorate elegant cu ganache de ciocolată. O combinație rafinată între dulceața vaniliei și intensitatea cacao-ului.",
                            ImageUrl = "/images/products/vanilla_chocolate.png",
                            Name = "Vanilla Cream Chocolate Petits",
                            Price = 7.9000000000000004
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Cake",
                            Description = "Éclair delicat umplut cu cremă fină de caramel și acoperit cu glazură catifelată și crumble crocant. Un desert rafinat inspirat din patiseria franțuzească clasică.",
                            ImageUrl = "/images/products/eclair.png",
                            Name = "Caramel Éclair Royale",
                            Price = 11.9
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Cake",
                            Description = "Mini prăjituri rafinate cu straturi delicate de mousse de căpșuni și cremă fină de vanilie, decorate elegant pentru un aspect premium.",
                            ImageUrl = "/images/products/strawberry_vanilla_squares.png",
                            Name = "Strawberry Vanilla Petit Squares",
                            Price = 10.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
